lab4 : main.o MinMaxHeap.o 
	g++  main.o MinMaxHeap.o -o lab7 
main.o   : main.cpp
	g++ -c main.cpp 	 
BinarySearchTree.o: BinarySearchTree.h BinarySearchTree.cpp
	g++ -c MinMaxHeap.cpp  
#Timer.o: Timer.
#	g++ -c Timer.h
#experiment.o: experiment.h
#	g++ -c experiment.h
clean :
	rm *.o 

