lab9 : main.o BinomialQueue.o 
	g++  main.o BinomialQueue.o -o lab9 
main.o   : main.cpp
	g++ -c main.cpp 	 
BinarySearchTree.o: BinomialQueue.h BinomialQueue.cpp
	g++ -c BinomialQueue.cpp BNode.h 
#Timer.o: Timer.
#	g++ -c Timer.h
#experiment.o: experiment.h
#	g++ -c experiment.h
clean :
	rm *.o 
