lab11 : main.o DisjointSets.o 
	g++  main.o DisjointSets.o -o lab11 
main.o   : main.cpp
	g++ -c main.cpp 	 
DisjointSets.o: DisjointSets.cpp
	g++ -c DisjointSets.cpp  
#Timer.o: Timer.
#	g++ -c Timer.h
#experiment.o: experiment.h
#	g++ -c experiment.h
clean :
	rm *.o 

